
package mtx_sandbox_api.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FlightsUpdateApiService", targetNamespace = "http://mtx-sandbox-api/services")
public class FlightsUpdateApiService
    extends Service
{

    private final static URL FLIGHTSUPDATEAPISERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTSUPDATEAPISERVICE_EXCEPTION;
    private final static QName FLIGHTSUPDATEAPISERVICE_QNAME = new QName("http://mtx-sandbox-api/services", "FlightsUpdateApiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/frank/personal/javeriana/Semestre_II/Implementacion/workspace/taller-soa-eai/src/main/resources/wsdl/ext/flights-update.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTSUPDATEAPISERVICE_WSDL_LOCATION = url;
        FLIGHTSUPDATEAPISERVICE_EXCEPTION = e;
    }

    public FlightsUpdateApiService() {
        super(__getWsdlLocation(), FLIGHTSUPDATEAPISERVICE_QNAME);
    }

    public FlightsUpdateApiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTSUPDATEAPISERVICE_QNAME, features);
    }

    public FlightsUpdateApiService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTSUPDATEAPISERVICE_QNAME);
    }

    public FlightsUpdateApiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTSUPDATEAPISERVICE_QNAME, features);
    }

    public FlightsUpdateApiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightsUpdateApiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FlightsUpdateApi
     */
    @WebEndpoint(name = "FlightsUpdateApiPort")
    public FlightsUpdateApi getFlightsUpdateApiPort() {
        return super.getPort(new QName("http://mtx-sandbox-api/services", "FlightsUpdateApiPort"), FlightsUpdateApi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FlightsUpdateApi
     */
    @WebEndpoint(name = "FlightsUpdateApiPort")
    public FlightsUpdateApi getFlightsUpdateApiPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://mtx-sandbox-api/services", "FlightsUpdateApiPort"), FlightsUpdateApi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTSUPDATEAPISERVICE_EXCEPTION!= null) {
            throw FLIGHTSUPDATEAPISERVICE_EXCEPTION;
        }
        return FLIGHTSUPDATEAPISERVICE_WSDL_LOCATION;
    }

}
