
package mtx_sandbox_api.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightsUpdateApi", targetNamespace = "http://mtx-sandbox-api/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightsUpdateApi {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "update")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://mtx-sandbox-api/services", className = "mtx_sandbox_api.services.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://mtx-sandbox-api/services", className = "mtx_sandbox_api.services.UpdateResponse")
    public String update(
        @WebParam(name = "request", targetNamespace = "")
        FlightUpdateRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "sendMopp")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMopp", targetNamespace = "http://mtx-sandbox-api/services", className = "mtx_sandbox_api.services.SendMopp")
    @ResponseWrapper(localName = "sendMoppResponse", targetNamespace = "http://mtx-sandbox-api/services", className = "mtx_sandbox_api.services.SendMoppResponse")
    public String sendMopp(
        @WebParam(name = "request", targetNamespace = "")
        MoppRequest request);

}
