
package bpel.com.oracle.xmlns.gestioneventosvuelos.eventosaereos.bpeleventosaerolineasla;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import bpel.aerolineas_latinoamericanas.contract.messages.AircratlineMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BPELEventosAerolineasLA", targetNamespace = "http://xmlns.oracle.com/GestionEventosVuelos/EventosAereos/BPELEventosAerolineasLA")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    bpel.aerolineas_latinoamericanas.contract.messages.ObjectFactory.class,
    bpel.org.example.salida.ObjectFactory.class
})
public interface BPELEventosAerolineasLA {


    /**
     * 
     * @param payload
     */
    @WebMethod(action = "process")
    @Oneway
    public void process(
        @WebParam(name = "aircratline-message", targetNamespace = "http://aerolineas-latinoamericanas/contract/messages", partName = "payload")
        AircratlineMessage payload);

}
