
package co.com.ws.cancel_flight;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CancelFlightEndpoint", targetNamespace = "http://cancel-flight.ws.com.co")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CancelFlightEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns co.com.ws.cancel_flight.CancelFlightResponse
     */
    @WebMethod(action = "http://cancel-flight.ws.com.co")
    @WebResult(name = "cancelFlightResponse", targetNamespace = "http://cancel-flight.ws.com.co", partName = "out")
    public CancelFlightResponse cancelFlight(
        @WebParam(name = "cancelFlightRequest", targetNamespace = "http://cancel-flight.ws.com.co", partName = "in")
        CancelFlightRequest in);

}
