
package co.com.ws.cancel_flight;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CancelFlightEndpointService", targetNamespace = "http://cancel-flight.ws.com.co", wsdlLocation = "file:/home/frank/Escritorio/wsdl/cancel-flight.wsdl")
public class CancelFlightEndpointService
    extends Service
{

    private final static URL CANCELFLIGHTENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CANCELFLIGHTENDPOINTSERVICE_EXCEPTION;
    private final static QName CANCELFLIGHTENDPOINTSERVICE_QNAME = new QName("http://cancel-flight.ws.com.co", "CancelFlightEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/frank/Escritorio/wsdl/cancel-flight.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANCELFLIGHTENDPOINTSERVICE_WSDL_LOCATION = url;
        CANCELFLIGHTENDPOINTSERVICE_EXCEPTION = e;
    }

    public CancelFlightEndpointService() {
        super(__getWsdlLocation(), CANCELFLIGHTENDPOINTSERVICE_QNAME);
    }

    public CancelFlightEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANCELFLIGHTENDPOINTSERVICE_QNAME, features);
    }

    public CancelFlightEndpointService(URL wsdlLocation) {
        super(wsdlLocation, CANCELFLIGHTENDPOINTSERVICE_QNAME);
    }

    public CancelFlightEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANCELFLIGHTENDPOINTSERVICE_QNAME, features);
    }

    public CancelFlightEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CancelFlightEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CancelFlightEndpoint
     */
    @WebEndpoint(name = "CancelFlightEndpoint")
    public CancelFlightEndpoint getCancelFlightEndpoint() {
        return super.getPort(new QName("http://cancel-flight.ws.com.co", "CancelFlightEndpoint"), CancelFlightEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CancelFlightEndpoint
     */
    @WebEndpoint(name = "CancelFlightEndpoint")
    public CancelFlightEndpoint getCancelFlightEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://cancel-flight.ws.com.co", "CancelFlightEndpoint"), CancelFlightEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANCELFLIGHTENDPOINTSERVICE_EXCEPTION!= null) {
            throw CANCELFLIGHTENDPOINTSERVICE_EXCEPTION;
        }
        return CANCELFLIGHTENDPOINTSERVICE_WSDL_LOCATION;
    }

}
