
package co.com.ws.on_air_shopping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OnAirShoppingEndpoint", targetNamespace = "http://on-air-shopping.ws.com.co")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OnAirShoppingEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns co.com.ws.on_air_shopping.OnAirShoppingResponse
     */
    @WebMethod(action = "http://on-air-shopping.ws.com.co")
    @WebResult(name = "onAirShoppingResponse", targetNamespace = "http://on-air-shopping.ws.com.co", partName = "out")
    public OnAirShoppingResponse create(
        @WebParam(name = "onAirShoppingRequest", targetNamespace = "http://on-air-shopping.ws.com.co", partName = "in")
        OnAirShoppingRequest in);

}
