
package co.com.ws.alert_on_air;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlertOnAirEndpointService", targetNamespace = "http://alert-on-air.ws.com.co", wsdlLocation = "file:/opt/soa/esb/jboss-fuse-6.3.0.redhat-187/deploy/wsdl/alert-on-air.wsdl")
public class AlertOnAirEndpointService
    extends Service
{

    private final static URL ALERTONAIRENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALERTONAIRENDPOINTSERVICE_EXCEPTION;
    private final static QName ALERTONAIRENDPOINTSERVICE_QNAME = new QName("http://alert-on-air.ws.com.co", "AlertOnAirEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/opt/soa/esb/jboss-fuse-6.3.0.redhat-187/deploy/wsdl/alert-on-air.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALERTONAIRENDPOINTSERVICE_WSDL_LOCATION = url;
        ALERTONAIRENDPOINTSERVICE_EXCEPTION = e;
    }

    public AlertOnAirEndpointService() {
        super(__getWsdlLocation(), ALERTONAIRENDPOINTSERVICE_QNAME);
    }

    public AlertOnAirEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALERTONAIRENDPOINTSERVICE_QNAME, features);
    }

    public AlertOnAirEndpointService(URL wsdlLocation) {
        super(wsdlLocation, ALERTONAIRENDPOINTSERVICE_QNAME);
    }

    public AlertOnAirEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALERTONAIRENDPOINTSERVICE_QNAME, features);
    }

    public AlertOnAirEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlertOnAirEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlertOnAirEndpoint
     */
    @WebEndpoint(name = "AlertOnAirEndpoint")
    public AlertOnAirEndpoint getAlertOnAirEndpoint() {
        return super.getPort(new QName("http://alert-on-air.ws.com.co", "AlertOnAirEndpoint"), AlertOnAirEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlertOnAirEndpoint
     */
    @WebEndpoint(name = "AlertOnAirEndpoint")
    public AlertOnAirEndpoint getAlertOnAirEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://alert-on-air.ws.com.co", "AlertOnAirEndpoint"), AlertOnAirEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALERTONAIRENDPOINTSERVICE_EXCEPTION!= null) {
            throw ALERTONAIRENDPOINTSERVICE_EXCEPTION;
        }
        return ALERTONAIRENDPOINTSERVICE_WSDL_LOCATION;
    }

}
