
package co.com.ws.maintenance_planner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaintenancePlannerEndpoint", targetNamespace = "http://maintenance-planner.ws.com.co")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MaintenancePlannerEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns co.com.ws.maintenance_planner.MaintenancePlannerResponse
     */
    @WebMethod(action = "http://maintenance-planner.ws.com.co")
    @WebResult(name = "maintenancePlannerResponse", targetNamespace = "http://maintenance-planner.ws.com.co", partName = "out")
    public MaintenancePlannerResponse sendMaintenance(
        @WebParam(name = "maintenancePlannerRequest", targetNamespace = "http://maintenance-planner.ws.com.co", partName = "in")
        MaintenancePlannerRequest in);

}
