//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 07:12:09 PM COT 
//


package co.com.canonical.flights;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the co.com.canonical.flights package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: co.com.canonical.flights
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FlightLegMessage }
     * 
     */
    public FlightLegMessage createFlightLegMessage() {
        return new FlightLegMessage();
    }

    /**
     * Create an instance of {@link FlightLeg }
     * 
     */
    public FlightLeg createFlightLeg() {
        return new FlightLeg();
    }

    /**
     * Create an instance of {@link FlightAttributes }
     * 
     */
    public FlightAttributes createFlightAttributes() {
        return new FlightAttributes();
    }

    /**
     * Create an instance of {@link Aircraft }
     * 
     */
    public Aircraft createAircraft() {
        return new Aircraft();
    }

    /**
     * Create an instance of {@link Usages }
     * 
     */
    public Usages createUsages() {
        return new Usages();
    }

    /**
     * Create an instance of {@link Airports }
     * 
     */
    public Airports createAirports() {
        return new Airports();
    }

    /**
     * Create an instance of {@link Dates }
     * 
     */
    public Dates createDates() {
        return new Dates();
    }

    /**
     * Create an instance of {@link Usage }
     * 
     */
    public Usage createUsage() {
        return new Usage();
    }

}
