//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.28 at 07:12:09 PM COT 
//


package co.com.canonical.flights;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="usage-parm">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="delta" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tsn" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="tso" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="tsi" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "usageParm",
    "delta",
    "tsn",
    "tso",
    "tsi"
})
public class Usage {

    @XmlElement(name = "usage-parm", required = true)
    protected String usageParm;
    protected double delta;
    protected double tsn;
    protected Double tso;
    protected Double tsi;

    /**
     * Gets the value of the usageParm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageParm() {
        return usageParm;
    }

    /**
     * Sets the value of the usageParm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageParm(String value) {
        this.usageParm = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     */
    public double getDelta() {
        return delta;
    }

    /**
     * Sets the value of the delta property.
     * 
     */
    public void setDelta(double value) {
        this.delta = value;
    }

    /**
     * Gets the value of the tsn property.
     * 
     */
    public double getTsn() {
        return tsn;
    }

    /**
     * Sets the value of the tsn property.
     * 
     */
    public void setTsn(double value) {
        this.tsn = value;
    }

    /**
     * Gets the value of the tso property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTso() {
        return tso;
    }

    /**
     * Sets the value of the tso property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTso(Double value) {
        this.tso = value;
    }

    /**
     * Gets the value of the tsi property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTsi() {
        return tsi;
    }

    /**
     * Sets the value of the tsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTsi(Double value) {
        this.tsi = value;
    }

}
