
package co.com.ws.maintenance_planner_mopp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MaintenancePlannerMoppEndpointService", targetNamespace = "http://maintenance-planner-mopp.ws.com.co")
public class MaintenancePlannerMoppEndpointService
    extends Service
{

    private final static URL MAINTENANCEPLANNERMOPPENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAINTENANCEPLANNERMOPPENDPOINTSERVICE_EXCEPTION;
    private final static QName MAINTENANCEPLANNERMOPPENDPOINTSERVICE_QNAME = new QName("http://maintenance-planner-mopp.ws.com.co", "MaintenancePlannerMoppEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/opt/soa/esb/jboss-fuse-6.3.0.redhat-187/deploy/wsdl//maintenance-planner-mopp.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAINTENANCEPLANNERMOPPENDPOINTSERVICE_WSDL_LOCATION = url;
        MAINTENANCEPLANNERMOPPENDPOINTSERVICE_EXCEPTION = e;
    }

    public MaintenancePlannerMoppEndpointService() {
        super(__getWsdlLocation(), MAINTENANCEPLANNERMOPPENDPOINTSERVICE_QNAME);
    }

    public MaintenancePlannerMoppEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAINTENANCEPLANNERMOPPENDPOINTSERVICE_QNAME, features);
    }

    public MaintenancePlannerMoppEndpointService(URL wsdlLocation) {
        super(wsdlLocation, MAINTENANCEPLANNERMOPPENDPOINTSERVICE_QNAME);
    }

    public MaintenancePlannerMoppEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAINTENANCEPLANNERMOPPENDPOINTSERVICE_QNAME, features);
    }

    public MaintenancePlannerMoppEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MaintenancePlannerMoppEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MaintenancePlannerMoppEndpoint
     */
    @WebEndpoint(name = "MaintenancePlannerMoppEndpoint")
    public MaintenancePlannerMoppEndpoint getMaintenancePlannerMoppEndpoint() {
        return super.getPort(new QName("http://maintenance-planner-mopp.ws.com.co", "MaintenancePlannerMoppEndpoint"), MaintenancePlannerMoppEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MaintenancePlannerMoppEndpoint
     */
    @WebEndpoint(name = "MaintenancePlannerMoppEndpoint")
    public MaintenancePlannerMoppEndpoint getMaintenancePlannerMoppEndpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://maintenance-planner-mopp.ws.com.co", "MaintenancePlannerMoppEndpoint"), MaintenancePlannerMoppEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAINTENANCEPLANNERMOPPENDPOINTSERVICE_EXCEPTION!= null) {
            throw MAINTENANCEPLANNERMOPPENDPOINTSERVICE_EXCEPTION;
        }
        return MAINTENANCEPLANNERMOPPENDPOINTSERVICE_WSDL_LOCATION;
    }

}
