
package co.com.ws.maintenance_planner_mopp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MaintenancePlannerMoppEndpoint", targetNamespace = "http://maintenance-planner-mopp.ws.com.co")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MaintenancePlannerMoppEndpoint {


    /**
     * 
     * @param in
     * @return
     *     returns co.com.ws.maintenance_planner_mopp.MoppResponse
     */
    @WebMethod(action = "http://maintenance-planner-mopp.ws.com.co")
    @WebResult(name = "moppResponse", targetNamespace = "http://maintenance-planner-mopp.ws.com.co", partName = "out")
    public MoppResponse sendMopp(
        @WebParam(name = "moppRequest", targetNamespace = "http://maintenance-planner-mopp.ws.com.co", partName = "in")
        MoppRequest in);

}
